services:
  omd:
    build: omd/
    platform: linux/amd64
    ports:
        - "127.0.0.3:60080:80"
        - "127.0.0.3:60443:443"
        - "127.0.0.3:60557:6557"
    volumes:
        - ../../../:/thruk:ro
        - ./:/test:ro
